on:
  push:
    branches:
      - master
name: Build Docker Container
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5.6
        name: Build & push Docker image
        with:
          image: ${{ secrets.REGISTRY_HOST }}/garrit.xyz
          tags: latest
          registry: ${{ secrets.DOCKER_REGISTRY }}
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}